### ISSUE TITLE
ROSEE Website improvements

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#1]
I open this issue with the aim to propose some suggestions to improve the ROSEE's website.

**Comment by lia2790** [comment]
I would want to suggest some changes in the first part of the homepage. As I said to Davide, in my opinion it is not so clear the following part

**changes proposed**

1) Package List (links to github repositories) :

    ROSEndEffector - the main package
    ROS End-Effector GUI - specific GUI for ROSEndEffector
    ROS End-Effector Gazebo Plugins - gazebo plugins to simply use the dnyamic simulato with ROSEndEffector
    rosee_msg - custom ROS messages specific for ROSEndEffector
    ROSEndEffectorDocs - the repository where this documentation is hosted
    ROSEndEffectorPackageManager - metapackage to easy installation


I mean, I don t understand the purpose of it.

2) in my opinion, the first sentence, this one 

ROS End-Effector package: provides a ROS-based set of standard interfaces to command robotics end-effectors in an agnostic fashion.


it is nice but I think it is too "spiegata", I mean I think it oculd be better to write a sentence a bit sorter and more immediate to understand, simpler. ( I think the doble dots are wrong).

**Comment by torydebra** [comment]
I modified the intro page putting github repo list at the end, related to #22 #21 #1
