### ISSUE TITLE
some error in the ROSEE DOC WEBSITE

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#10]
In this issue, **I will collect all the error** that I find in the ROSEE DOC WEBSITE through modified images.

**Comment by lia2790** [comment]
(https://advrhumanoids.github.io/ROSEndEffectorDocs/install.html#full-installation-suggested)

1) ![Schermata 2020-06-29 alle 15 17 12 (2)](https://user-images.githubusercontent.com/15608027/86010604-ed84ad00-ba1b-11ea-927a-bd539c6cb574.png)

2) ![Schermata 2020-06-29 alle 15 20 06 (2)](https://user-images.githubusercontent.com/15608027/86011101-93d0b280-ba1c-11ea-90a7-0825ffd5032a.png)

3) ![Schermata 2020-06-29 alle 15 24 39 (2)](https://user-images.githubusercontent.com/15608027/86011558-1c4f5300-ba1d-11ea-89b6-a9e13b13855c.png)

**Comment by lia2790** [comment]
at the following link (https://advrhumanoids.github.io/ROSEndEffectorDocs/usage.html) I suggest the following changes

1. ![Schermata 2020-06-29 alle 17 19 15 (2)](https://user-images.githubusercontent.com/15608027/86024938-ec5c7b80-ba2d-11ea-9591-87099a00d717.png)

2.  ![Schermata 2020-06-29 alle 17 29 46 (2)](https://user-images.githubusercontent.com/15608027/86026036-38f48680-ba2f-11ea-9b22-822a65325b7b.png)

3.  ![Schermata 2020-06-29 alle 17 39 19 (2)](https://user-images.githubusercontent.com/15608027/86026812-32b2da00-ba30-11ea-91a9-e9b670836f15.png)

4. ![Schermata 2020-06-29 alle 17 45 24 (2)](https://user-images.githubusercontent.com/15608027/86027537-20856b80-ba31-11ea-94ac-25bbfee22ca5.png)

5. ![Schermata 2020-06-29 alle 17 51 57 (2)](https://user-images.githubusercontent.com/15608027/86029013-ea48eb80-ba32-11ea-91e3-e5b23334a0fc.png)

6. <img width="1280" alt="Schermata 2020-06-29 alle 18 16 55" src="https://user-images.githubusercontent.com/15608027/86030649-08afe680-ba35-11ea-899b-e0f96ab730bb.png">

**Comment by lia2790** [comment]
https://advrhumanoids.github.io/ROSEndEffectorDocs/examples.html

1.  <img width="1280" alt="Schermata 2020-06-29 alle 21 16 48" src="https://user-images.githubusercontent.com/15608027/86047542-51749900-ba4f-11ea-97e2-2b91b353106c.png">

2. <img width="1280" alt="Schermata 2020-06-29 alle 21 29 02" src="https://user-images.githubusercontent.com/15608027/86048602-0f4c5700-ba51-11ea-86a8-021ec5a447ba.png">

3. <img width="1280" alt="Schermata 2020-06-29 alle 21 40 46" src="https://user-images.githubusercontent.com/15608027/86049005-a87b6d80-ba51-11ea-8ebe-18e8c4eb9645.png">

4. <img width="1280" alt="Schermata 2020-06-29 alle 21 45 18" src="https://user-images.githubusercontent.com/15608027/86049349-4b33ec00-ba52-11ea-99e8-d472f3ce7f86.png">

5. <img width="1280" alt="Schermata 2020-06-29 alle 21 49 13" src="https://user-images.githubusercontent.com/15608027/86049577-aebe1980-ba52-11ea-8799-5bb250e4bbc4.png">

**Comment by lia2790** [comment]
![Schermata 2020-07-03 alle 15 43 04 (2)](https://user-images.githubusercontent.com/15608027/86475328-ba585b80-bd44-11ea-9562-75f58abdb611.png)

**Comment by torydebra** [comment]
Ok, thanks for the feedbacks @lia2790 ! Following them I improved a bit the docs. I will close here
