### ISSUE TITLE
suggestion to change suggested with recommended 

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#11]
I open this issue with the aim to suggest to change the "tag" suggested with recommended inside the ROSEE documentation. 

I think if we really want to suggest a particular procedure, the "tag" recommended is better. I think It is better because it helps more in the choice since it gives you more "strongness" in the decision process.

![Schermata 2020-07-03 alle 14 31 40 (2)](https://user-images.githubusercontent.com/15608027/86469594-0225b580-bd3a-11ea-82a2-3e20a8db231d.png)

**Comment by torydebra** [comment]
Yes, probably in other docs they use recommended. Changed!
