### ISSUE TITLE
suggestion to insert the copy button in the code lines

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#12]
I open this issue with the aim to suggest to insert the copy button in the code lines of the online guide. 
I find it very practical.

To show the idea

![Schermata 2020-07-03 alle 14 47 24 (2)](https://user-images.githubusercontent.com/15608027/86470708-4619ba00-bd3c-11ea-9ca8-17eb84d1c651.png)

**Comment by torydebra** [comment]
Probably this https://sphinx-copybutton.readthedocs.io/en/latest/ can be useful

**Comment by lia2790** [comment]
top! exactly! that one! what do you think about it? Do you like it?

**Comment by torydebra** [comment]
Yes, we can add it to the TODO list of docs style improvements :D

**Comment by lia2790** [comment]
> Yes, we can add it to the TODO list of docs style improvements :D

where exactly please :)

**Comment by torydebra** [comment]
They are the issues here :D

**Comment by torydebra** [comment]
Done, nice one
