### ISSUE TITLE
suggestion to improve installation documentation 

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#13]
With this issue, I would like to suggest to insert just a sentence after the command lines to notify at the user to have completed the installation procedure, as an example: 

- If everything compiled correctly now you are ready to use our ROSEE powerful framework!
or
- Done! You are ready to use our ROSEE powerful framework!

And we could also provide to the user a ready test see that everything works well!

The point where I thought to insert that sentence is shown in the picture 
![Schermata 2020-07-03 alle 14 54 17 (2)](https://user-images.githubusercontent.com/15608027/86471744-38fdca80-bd3e-11ea-88c7-802bfc2f637d.png)

**Comment by torydebra** [comment]
yes, done! 
``` rst
You are now ready to use ROS End-Effector! Check :ref:`How to use ROS End-Effector with your end-effector <usage>` and :ref:`Examples with ready to use end-effectors <examples>` sections to learn how to use it.  
```
