### ISSUE TITLE
ROSEE offline command

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#14]
With this issue, I would like to suggest to make the ROSEE offline command finishing correctly.

**Comment by lia2790** [comment]
The point is that when the ROSEE offline command is run, it is not finished correctly, the terminal is not free to be used.

I would prefer that command leaves the terminal and close it definitely.

**Comment by torydebra** [comment]
It is a matter of `roslaunch`; when the main exits, if roslaunch has started roscore, the terminal remains occupied because of roscore remains active. Probably we can add a comment like : "after node has finished is it safe to `ctrl+c`"

**Comment by lia2790** [comment]
yeah, we could, but it is not so fancy. I mean I think it is not nice to write explicitly

**Comment by torydebra** [comment]
I found this https://answers.ros.org/question/188052/close-roscore-after-running-with-roslaunch/  but I do not like so much: it shutdown roscore with a terryfing red error:
```
================================================================================REQUIRED process [UniversalFindActions-2] has died!
process has finished cleanly
log file: /home/tori/.ros/log/cde51cc4-cb4f-11ea-b8d1-04d9f5c8ccde/UniversalFindActions-2*.log
Initiating shutdown!
================================================================================
```

I think the best solution is to remember this in the docs:

> It is a matter of `roslaunch`; when the main exits, if roslaunch has started roscore, the terminal remains occupied because of roscore remains active. Probably we can add a comment like : "after node has finished is it safe to `ctrl+c`"

**Comment by lia2790** [comment]
@liesrock have you any suggestion to fix this issue?

**Comment by lia2790** [comment]
> I found this https://answers.ros.org/question/188052/close-roscore-after-running-with-roslaunch/ but I do not like so much: it shutdown roscore with a terryfing red error:
> 
> ```
> ================================================================================REQUIRED process [UniversalFindActions-2] has died!
> process has finished cleanly
> log file: /home/tori/.ros/log/cde51cc4-cb4f-11ea-b8d1-04d9f5c8ccde/UniversalFindActions-2*.log
> Initiating shutdown!
> ================================================================================
> ```
> 
> I think the best solution is to remember this in the docs:
> 
> > It is a matter of `roslaunch`; when the main exits, if roslaunch has started roscore, the terminal remains occupied because of roscore remains active. Probably we can add a comment like : "after node has finished is it safe to `ctrl+c`"

Also, I think you can write simply: to exit press ctrl+c....
