### ISSUE TITLE
RESET button ROSEE GUI

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#15]
With this issue, I would like to suggest to insert a RESET button in the GUI.

**Comment by lia2790** [comment]
I think it would be usefull to insert in the GUI a button reset which allows you to put the fingers in its "normal" position, i.e., with 0%... it is a bit boring doing that manually with the slide bar...

**Comment by torydebra** [comment]
We have it; https://github.com/ADVRHumanoids/rosee_gui/issues/2. It is still in devel2 branch, though. But it will be integrated in the future GUI versions
