### ISSUE TITLE
ROSEE EXAMPLE qbhand error in procedure

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#19]
I open this issue because when I try to use ROSEE for qb softhand the procedure does not work. I guess It miss of some command to reach the desired goal. In particular the cd catkin_ws does not work.

**Comment by torydebra** [comment]
- Some cd ... instructions need to be corrected
- Also ros-kinetic-hardware-interface must be installed
- joint-limits-interface
- transmission-interface
- combined-robot-hw
- ....

UPDATE: all these are packages that can be installed togheter with the metapackage **ros-kinetic-ros-control**

**Comment by torydebra** [comment]
updated the docs accordingly
