### ISSUE TITLE
ROSEE DOCUMENTATION WELCOME possible improvements

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#21]
![Schermata 2020-07-10 alle 11 57 48 (2)](https://user-images.githubusercontent.com/15608027/87142794-53d3c000-c2a5-11ea-8b93-33e5781369cd.png)

**Comment by lia2790** [comment]
![Schermata 2020-07-10 alle 12 06 07 (2)](https://user-images.githubusercontent.com/15608027/87143565-9c3fad80-c2a6-11ea-8bf6-f431edc7efe5.png)

**Comment by torydebra** [comment]
I modified the intro page putting github repo list at the end, related to #22 #21 #1
