### ISSUE TITLE
ROSEE DOCUMENTATION WELCOME possible new features

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#22]
![Schermata 2020-07-10 alle 12 13 12 (2)](https://user-images.githubusercontent.com/15608027/87144419-03aa2d00-c2a8-11ea-9ae6-e4e464c7045b.png)

**Comment by torydebra** [comment]
I modified the intro page putting github repo list at the end, related to #22 #21 #1
