### ISSUE TITLE
possible improvements for ROSEE MAIN PACKAGE README

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#3]
Hi, for the Github's page of ROSEndEffector (the main package) (https://github.com/ADVRHumanoids/ROSEndEffector) I would like to improve the readme. I think It is poor in package information itself. I mean when I read the readme I do not understand what I can find in that package. 

I think we should add a brief description right here 

<img width="1280" alt="Schermata 2020-06-29 alle 10 29 19" src="https://user-images.githubusercontent.com/15608027/85991569-e77ad600-b9f3-11ea-96d6-da61f95a6dd3.png">

**Comment by torydebra** [comment]
I think it is better to not put too infos in readme, we have this sphinx doc for that !
