### ISSUE TITLE
possible improvements of ROSEE GUI PACKAGE README

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#4]
Hi, I think also here we can provide a better readme file for the package (https://github.com/ADVRHumanoids/rosee_gui). 

In particular these sections

<img width="1280" alt="Schermata 2020-06-29 alle 10 45 03" src="https://user-images.githubusercontent.com/15608027/85993032-037f7700-b9f6-11ea-8be3-6b9bef1feca9.png">

**I should provide a better and brief introduction of each ( just a sentence )**

**Comment by lia2790** [comment]
It would be **pretty cool** also insert some cool image about the GUI!!!!! some GIF or video! 
they are very pretty cool! And I think they could really improve the impact of the package!

**Comment by torydebra** [comment]
Hi,
About all the readme issues, they are an old version (when we had not the rosee nice docs). You should look at the devel branches, that will be merged in master soon, reamdes included.

Also I think that videos and images of GUI should be all put in the readthedocs documentations, to not have multiple informations spreaded among all the readmes

**Comment by lia2790** [comment]
I agree to have not multiple replicated information. Ok, I understand the point of the devel branch etc.

**Comment by torydebra** [comment]
Also see #3
