### ISSUE TITLE
possible improvements for ROSEE GAZEBO PLUGIN README

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#5]
I have some suggestions to improve the readme.
(https://github.com/ADVRHumanoids/rosee_gazebo_plugins)

1) <img width="1277" alt="Schermata 2020-06-29 alle 10 57 18" src="https://user-images.githubusercontent.com/15608027/86001898-df309400-ba0f-11ea-979e-174f30cbe703.png">

2) <img width="1280" alt="Schermata 2020-06-29 alle 11 09 48" src="https://user-images.githubusercontent.com/15608027/86003758-8c0c1080-ba12-11ea-9454-ffc80fe95dcd.png">

3) ![Schermata 2020-06-29 alle 14 13 17 (2)](https://user-images.githubusercontent.com/15608027/86004029-f624b580-ba12-11ea-86f7-af5d1db489fc.png)

4) ![Schermata 2020-06-29 alle 14 16 26 (2)](https://user-images.githubusercontent.com/15608027/86005338-ce365180-ba14-11ea-9c7c-51ea8c2a931c.png)

5) ![Schermata 2020-06-29 alle 14 28 50 (2)](https://user-images.githubusercontent.com/15608027/86005898-849a3680-ba15-11ea-8f4b-9b57d3ebec24.png)

**Comment by torydebra** [comment]
see #4
