### ISSUE TITLE
possible improvements for ROSEE MSG README

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#6]
A suggestion to improve the readme of the rosee_msg pakcage (https://github.com/ADVRHumanoids/rosee_msg). 

![Schermata 2020-06-29 alle 14 45 02 (2)](https://user-images.githubusercontent.com/15608027/86007394-9d0b5080-ba17-11ea-86d0-110407d237d2.png)

**Comment by torydebra** [comment]
see #4
