### ISSUE TITLE
possible improvements for ROSEE DOC README

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/ROSEndEffectorDocs#7]
A suggestion to improve the readme of the rosee doc package (https://github.com/ADVRHumanoids/ROSEndEffectorDocs). 

![Schermata 2020-06-29 alle 14 51 32 (2)](https://user-images.githubusercontent.com/15608027/86007977-7bf72f80-ba18-11ea-9f02-4bc385d63352.png)

**Comment by torydebra** [comment]
Modified so the rendered version is put at the very begin
